#!/usr/bin/env node
/**
 *   node label-cli.mjs check <barcode>        verify or complete a GS1 check digit
 *   node label-cli.mjs lint <file.zpl>        find what the printer will silently drop
 *
 * The lint is the one worth running on ZPL you did not write. A Zebra printer
 * has no back channel: it accepts every byte you send and tells you nothing.
 */
import fs from "node:fs/promises";
import { gs1CheckDigit, verifyGs1, GTIN_LENGTHS } from "./barcodes.mjs";
import { DPMM } from "./zpl.mjs";

/**
 * Lint raw ZPL — including ZPL generated by something else.
 *
 * Deliberately shallow: it reads ^PW, ^FO and ^FD and nothing more. A full ZPL
 * parser would be wrong more often than useful, and these three commands carry
 * the failures that actually reach an operator.
 */
export function lintZpl(zpl, { dpi = 203 } = {}) {
    const issues = [];
    const text = String(zpl);

    if (!text.includes("^XA")) issues.push({ code: "NO_FORMAT_START", message: "No ^XA — the printer will not treat this as a label format." });
    if (!text.includes("^XZ")) issues.push({ code: "NO_FORMAT_END", message: "No ^XZ — the printer buffers the format and prints nothing." });

    const pw = /\^PW(\d+)/.exec(text);
    const ll = /\^LL(\d+)/.exec(text);
    const width = pw ? Number(pw[1]) : null;
    const height = ll ? Number(ll[1]) : null;
    if (!pw) {
        issues.push({
            code: "NO_PRINT_WIDTH",
            message: "No ^PW. The printer falls back to its configured width, so the same ZPL lays out differently on two printers.",
            fix: "Emit ^PW<dots> from the label's real width and the printer's dpi.",
        });
    }

    // ^FO x,y — origins outside the declared label.
    if (width !== null) {
        for (const m of text.matchAll(/\^FO(\d+),(\d+)/g)) {
            const x = Number(m[1]);
            const y = Number(m[2]);
            if (x >= width) issues.push({ code: "ORIGIN_OFF_LABEL", message: `^FO${x},${y} starts past the declared width (${width} dots). Nothing at that origin prints.` });
            else if (height !== null && y >= height) issues.push({ code: "ORIGIN_OFF_LABEL", message: `^FO${x},${y} starts past the declared length (${height} dots).` });
        }
    }

    // ^FD data carrying a command prefix without ^FH.
    for (const m of text.matchAll(/(\^FH)?\^FD([\s\S]*?)\^FS/g)) {
        const hasFh = Boolean(m[1]);
        const data = m[2];
        if (!hasFh && /[\^~]/.test(data)) {
            issues.push({
                code: "UNESCAPED_CONTROL_CHAR",
                message: `^FD data contains ^ or ~ without ^FH: ${JSON.stringify(data.slice(0, 30))}. The printer reads it as a command.`,
                fix: "Emit ^FH before ^FD and hex-escape those bytes as _5E / _7E.",
            });
        }
    }

    if (width !== null) {
        const mm = (width / DPMM[dpi]).toFixed(1);
        issues.push({ code: "INFO_GEOMETRY", severity: "info", message: `^PW${width} is ${mm}mm at ${dpi} dpi. If the stock is a different width, this ZPL is for a different printer.` });
    }
    return issues;
}

function checkCommand(code) {
    const s = String(code).replace(/\s/g, "");
    if (!/^\d+$/.test(s)) return `Not a digit string: ${JSON.stringify(code)}\n`;
    const named = Object.entries(GTIN_LENGTHS).filter(([, len]) => len === s.length).map(([k]) => k);
    const L = [];
    if (named.length) {
        const ok = verifyGs1(s);
        L.push(`${s}   ${named.join(" / ")}`);
        L.push(ok ? "  check digit OK" : `  check digit WRONG — last digit is ${s.at(-1)}, should be ${gs1CheckDigit(s.slice(0, -1))}`);
        L.push(`  correct code: ${s.slice(0, -1)}${gs1CheckDigit(s.slice(0, -1))}`);
    } else {
        const complete = `${s}${gs1CheckDigit(s)}`;
        const asName = Object.entries(GTIN_LENGTHS).filter(([, len]) => len === complete.length).map(([k]) => k);
        L.push(`${s}   ${s.length} digits — treating it as a payload without a check digit`);
        L.push(`  with check digit: ${complete}${asName.length ? `   (${asName.join(" / ")})` : ""}`);
    }
    return L.join("\n") + "\n";
}

if (import.meta.url === `file://${process.argv[1]}`) {
    const [cmd, arg, ...rest] = process.argv.slice(2);
    if (cmd === "check" && arg) {
        process.stdout.write(checkCommand(arg));
    } else if (cmd === "lint" && arg) {
        const dpiFlag = rest.includes("--dpi") ? Number(rest[rest.indexOf("--dpi") + 1]) : 203;
        const issues = lintZpl(await fs.readFile(arg, "utf8"), { dpi: dpiFlag });
        const real = issues.filter((i) => i.severity !== "info");
        for (const i of issues) {
            process.stdout.write(`${i.severity === "info" ? "  " : "! "}${i.code}: ${i.message}\n`);
            if (i.fix) process.stdout.write(`   ${i.fix}\n`);
        }
        if (!real.length) process.stdout.write("No problems found.\n");
        process.exitCode = real.length ? 1 : 0;
    } else {
        process.stderr.write("usage:\n  label-cli.mjs check <barcode>\n  label-cli.mjs lint <file.zpl> [--dpi 300]\n");
        process.exit(2);
    }
}
